version: '3'

services:
  app:
    container_name: FastAPI
    environment:
      - DB_string=$mongo_DB_string
      - DB_name=$mongo_DB_name
      - DB_collection=$mongo_DB_collection
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - "8082:8082"
    command: uvicorn main:app --reload --host 0.0.0.0 --port 8082